[general]
import = [
    "~/.config/alacritty/gruvbox_theme/gruvbox_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 20
padding.y = 20
decorations = "Buttonless"
opacity = 1
blur = true

[bell]
animation = "EaseOutExpo"
duration = 0

[font]
normal.family = "Hack Nerd Font"
size = 18.0

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  # General
  {key = "T", mods = "Command", action = "None"},
  {key = "N", mods = "Command", action = "None"},
  {key = "W", mods = "Command", action = "Quit"},
  {key = "F", mods = "Command|Control|Shift|Alt", action = "ToggleFullscreen"},
  # Tmux general
  {key = "R", mods = "Command|Control|Shift|Alt", chars = "\u0001R"}, # Reload Tmux config
  {key = "U", mods = "Command|Control|Shift|Alt", chars = "\u0001U"}, # Update Tmux plugins
  {key = "I", mods = "Command|Control|Shift|Alt", chars = "\u0001I"}, # Install Tmux plugins
  {key = "X", mods = "Command|Control|Shift|Alt", chars = "\u0001x"}, # Kill session/window/pane
  {key = "M", mods = "Command|Control|Shift|Alt", chars = "\u0001m"}, # Maximize pane
  ## Sessions
  {key = "S", mods = "Command|Control|Shift|Alt", chars = "\u0001s"}, # Choose session
  {key = "D", mods = "Command|Control|Shift|Alt", chars = "\u0001d"}, # Detach session
  {key = "N", mods = "Command|Control|Shift|Alt", chars = "\u0001a"}, # New session
  {key = "4", mods = "Command|Control|Shift|Alt", chars = "\u0001$"}, # Rename session
  ## Windows
  {key = "W", mods = "Command|Control|Shift|Alt", chars = "\u0001&"}, # Close window
  {key = "T", mods = "Command|Control|Shift|Alt", chars = "\u0001c"}, # New window
  {key = "L", mods = "Command|Control|Shift|Alt", chars = "\u0001n"}, # Next window
  {key = "H", mods = "Command|Control|Shift|Alt", chars = "\u0001p"}, # Previous window
  {key = ",", mods = "Command|Control|Shift|Alt", chars = "\u0001,"}, # Rename window
  ## Panes
  {key = "\\" , mods = "Command|Control|Shift|Alt", chars = "\u0001%"}, # Vertical split
  {key = '-' , mods = "Command|Control|Shift|Alt", chars = "\u0001-"}, # Horizontal split
  # Copy mode
  {key = '[' , mods = "Command|Control|Shift|Alt", chars = "\u0001["}, # Enter Copy mode
]
